name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
     
      - name: Run API tests
        run: |
          postman collection run https://api.postman.com/collections/21611409-9843529e-22e1-41a8-a0d3-e96999e53638?access_key=${{ secrets.OKSANA }} -e 'data.json'
          # Lint your API using Postman CLI
          postman api lint
